/* ============================================================
   FRIEND GAME ZONE — offline mini-games
   No fetch(), no API calls, no backend dependency.
   ============================================================ */
(() => {
  // Play Corner is a private surprise. It is unlocked only after the quiz
  // result page records a score strictly greater than 5. The games themselves
  // never call the backend.
  const savedScore = Number(localStorage.getItem('lastFriendScore') || 0);
  const savedTotal = Number(localStorage.getItem('lastFriendTotal') || 0);
  const unlocked = Number.isFinite(savedScore) && Number.isFinite(savedTotal) && savedTotal > 0 && savedScore >= 6;
  const gamesPage = document.getElementById('gamesPage');
  const lockedPanel = document.getElementById('gamesLocked');
  if (!unlocked) {
    if (gamesPage) gamesPage.querySelectorAll(':scope > section:not(#gamesLocked)').forEach(section => section.hidden = true);
    if (lockedPanel) lockedPanel.hidden = false;
    return;
  }
  const unlockText = document.getElementById('gameUnlockText');
  if (unlockText) unlockText.textContent = `Unlocked for you: ${savedScore}/${savedTotal} — this private Play Corner is your surprise!`;

  const modal = document.getElementById('gameModal');
  const stage = document.getElementById('gameStage');
  const title = document.getElementById('modalTitle');
  const subtitle = document.getElementById('modalSubtitle');
  const close = () => { modal.classList.remove('is-open'); modal.setAttribute('aria-hidden','true'); stage.innerHTML=''; };
  document.getElementById('closeGame').onclick=close;
  modal.querySelector('[data-close-game]').onclick=close;
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('is-open'))close();});

  const esc = s => String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const rand = (n)=>Math.floor(Math.random()*n);
  const shuffle = a => { for(let i=a.length-1;i>0;i--){const j=rand(i+1);[a[i],a[j]]=[a[j],a[i]];} return a; };
  const wait = ms => new Promise(r=>setTimeout(r,ms));
  const setStage = (t,s,fn) => {title.textContent=t;subtitle.textContent=s;stage.innerHTML='';fn(stage);modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');};

  document.querySelectorAll('.filter-btn').forEach(btn=>btn.onclick=()=>{
    document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active')); btn.classList.add('active');
    const f=btn.dataset.filter;document.querySelectorAll('.game-card').forEach(c=>c.style.display=f==='all'||c.dataset.type===f?'flex':'none');
  });
  document.querySelectorAll('.game-launch').forEach(b=>b.onclick=()=>openGame(b.dataset.open));

  function toolbar(stage,scoreText,resetFn){
    const bar=document.createElement('div');bar.className='game-toolbar';
    const score=document.createElement('span');score.className='game-score';score.textContent=scoreText;
    const reset=document.createElement('button');reset.className='mini-control';reset.textContent='Restart';reset.onclick=resetFn;bar.append(score,reset);stage.append(bar);return score;
  }

  function ludo(stage){
    let you=0,bots=[0,0,0],turn='you',round=0; const total=40;
    const draw=()=>{stage.innerHTML='';const score=toolbar(stage,`You: ${you} · Bots: ${bots.join(' / ')}`,draw);const msg=document.createElement('div');msg.className='game-message';stage.append(msg);const board=document.createElement('div');board.className='ludo-board';
      for(let i=1;i<=total;i++){const c=document.createElement('div');c.className='ludo-cell';c.textContent=i;if(i===you&&you>0){const p=document.createElement('span');p.className='pawn you';c.append(p)}bots.forEach((v,k)=>{if(v===i&&v>0){const p=document.createElement('span');p.className='pawn bot'+(k+1);c.append(p)}});board.append(c)}stage.append(board);
      const roll=document.createElement('button');roll.className='mini-control';roll.textContent='Roll Dice';roll.disabled=turn!=='you';stage.append(roll);roll.onclick=()=>{const d=1+rand(6);you=Math.min(total,you+d);round++;msg.textContent=`You rolled ${d}.`;if(you>=total){msg.textContent='You reached the finish first!';roll.disabled=true;return}turn='bots';roll.disabled=true;setTimeout(()=>{bots=bots.map(v=>Math.min(total,v+1+rand(6)));if(bots.some(v=>v>=total)){msg.textContent='A bot reached the finish! Try again.';roll.disabled=true;return}turn='you';roll.disabled=false;draw();},700)};
    };draw();
  }

  function carrom(stage){
    let score=0,shots=0;function draw(){stage.innerHTML='';const sc=toolbar(stage,`Pocketed: ${score} · Shots: ${shots}`,draw);const msg=document.createElement('div');msg.className='game-message';msg.textContent='Your turn — take the shot. Then the bot will play automatically.';stage.append(msg);const board=document.createElement('div');board.className='carrom-board';for(let i=0;i<4;i++){const h=document.createElement('div');h.className='carrom-hole';board.append(h)}const center=document.createElement('div');center.className='carrom-center';board.append(center);for(let i=0;i<7;i++){const p=document.createElement('span');p.className='carrom-piece';p.style.left=(38+rand(24))+'%';p.style.top=(38+rand(24))+'%';p.style.background=i===0?'#2d2521':'#e8d5bd';board.append(p)}const aim=document.createElement('div');aim.className='carrom-aim';board.append(aim);const striker=document.createElement('button');striker.className='striker';striker.setAttribute('aria-label','shoot');board.append(striker);stage.append(board);striker.onclick=async()=>{shots++;if(Math.random()<.58){score++;msg.textContent='Nice pocket! Your turn is done — bot is taking its automatic turn…';}else msg.textContent='Missed! Bot is taking its automatic turn…';striker.disabled=true;setTimeout(()=>{if(Math.random()<.45){score=Math.max(0,score-0);msg.textContent='🤖 Bot pocketed one. Your turn!';}else msg.textContent='🤖 Bot missed. Your turn!';draw()},650)};}draw();}

  function snakes(stage){
    let you=1,bot=1,turn=true;const jumps={16:6,47:26,49:11,56:53,62:19,64:60,87:24,93:73,95:75,98:78,1:38,4:14,9:31,21:42,28:84,36:44,51:67,71:91,80:100};
    const move=(v,d)=>{v=Math.min(100,v+d);return jumps[v]||v};
    const draw=()=>{stage.innerHTML='';const sc=toolbar(stage,`You: ${you} · Bot: ${bot}`,draw);const msg=document.createElement('div');msg.className='game-message';stage.append(msg);const board=document.createElement('div');board.className='snake-board';for(let i=100;i>=1;i--){const c=document.createElement('div');c.className='snake-cell';c.textContent=i;if(i===you)c.innerHTML='<span class="pawn you"></span>'+i;if(i===bot)c.innerHTML+='<span class="pawn bot1"></span>'+i;if(jumps[i])c.style.fontWeight='1000';board.append(c)}stage.append(board);const roll=document.createElement('button');roll.className='mini-control';roll.textContent='Roll Dice';stage.append(roll);roll.onclick=()=>{const d=1+rand(6);you=move(you,d);msg.textContent=`You rolled ${d}.`;if(you===100){msg.textContent='You win the race!';roll.disabled=true;return}roll.disabled=true;setTimeout(()=>{const bd=1+rand(6);bot=move(bot,bd);if(bot===100){msg.textContent='Bot reached 100 first!';roll.disabled=true;return}msg.textContent=`Bot rolled ${bd}. Your turn!`;roll.disabled=false;draw()},650)};};draw();}

  function tictactoe(stage){let cells=Array(9).fill(''),turn='X',over=false;const win=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];const result=()=>win.find(a=>a.every(i=>cells[i]===turn));const draw=()=>{stage.innerHTML='';const sc=toolbar(stage,'You are X · Bot is O',draw);const msg=document.createElement('div');msg.className='game-message';msg.textContent=turn==='X'?'Your turn.':'';stage.append(msg);const board=document.createElement('div');board.className='tic-board';cells.forEach((v,i)=>{const b=document.createElement('button');b.className='tic-cell '+(v.toLowerCase());b.textContent=v;b.onclick=()=>{if(over||cells[i])return;cells[i]='X';turn='X';if(win.some(a=>a.every(j=>cells[j]==='X'))){over=true;msg.textContent='You win!';draw();return}if(cells.every(Boolean)){over=true;msg.textContent='Draw!';draw();return}turn='O';draw();setTimeout(bot,420)};board.append(b)});stage.append(board);function bot(){if(over)return;const empty=cells.map((v,i)=>v?null:i).filter(i=>i!==null);let pick=empty.includes(4)?4:empty[rand(empty.length)];cells[pick]='O';if(win.some(a=>a.every(j=>cells[j]==='O'))){over=true;msg.textContent='Bot wins this round.'}else if(cells.every(Boolean)){over=true;msg.textContent='Draw!'}else turn='X';draw()} };draw();}

  function chess(stage){
    const pieces=['♜','♞','♝','♛','♚','♝','♞','♜','♟','♟','♟','♟','♟','♟','♟','♟','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','♙','♙','♙','♙','♙','♙','♙','♙','♖','♘','♗','♕','♔','♗','♘','♖'];
    let board=[...pieces],selected=-1,turn='white';
    const isWhite=p=>['♙','♖','♘','♗','♕','♔'].includes(p),isBlack=p=>['♟','♜','♞','♝','♛','♚'].includes(p);
    const draw=()=>{stage.innerHTML='';toolbar(stage,'Simple offline chess · You: White · Bot: Black',draw);const msg=document.createElement('div');msg.className='chess-note';msg.textContent='Click a white piece, then click a destination. The bot makes a simple automatic reply.';stage.append(msg);const b=document.createElement('div');b.className='chess-board';board.forEach((p,i)=>{const c=document.createElement('button');c.className='chess-cell '+((Math.floor(i/8)+i)%2?'dark':'light')+(selected===i?' selected':'');c.textContent=p;c.onclick=()=>click(i);b.append(c)});stage.append(b)};
    function click(i){if(turn!=='white')return;if(selected<0){if(isWhite(board[i])){selected=i;draw()}return}if(i===selected){selected=-1;draw();return}if(board[i]&&isWhite(board[i])){selected=i;draw();return}if(Math.abs(i-selected)>16&&board[selected]==='♙'){selected=-1;draw();return}board[i]=board[selected];board[selected]='';selected=-1;turn='black';draw();setTimeout(bot,500)}
    function bot(){const choices=[];board.forEach((p,i)=>{if(isBlack(p)){const candidates=[i+8,i+7,i+9,i+1,i-1];candidates.forEach(j=>{if(j>=0&&j<64&&(!board[j]||isWhite(board[j])))choices.push([i,j])})}});if(!choices.length){turn='white';draw();return}const [a,z]=choices[rand(choices.length)];board[z]=board[a];board[a]='';turn='white';draw()}
    draw();
  }

  function memory(stage){let deck=shuffle(['A','A','B','B','C','C','D','D','E','E','F','F','G','G','H','H']),open=[],matched=new Set(),moves=0;const draw=()=>{stage.innerHTML='';toolbar(stage,`Pairs: ${matched.size}/8 · Moves: ${moves}`,draw);const board=document.createElement('div');board.className='memory-board';deck.forEach((v,i)=>{const b=document.createElement('button');b.className='memory-card '+(open.includes(i)?'flipped ':'')+(matched.has(i)?'matched':'');b.textContent=(open.includes(i)||matched.has(i))?v:'?';b.onclick=()=>flip(i,b);board.append(b)});if(matched.size===8){const m=document.createElement('div');m.className='game-message';m.textContent=`All pairs matched in ${moves} moves!`;stage.append(m)}stage.append(board);function flip(i,b){if(open.length===2||open.includes(i)||matched.has(i))return;open.push(i);b.classList.add('flipped');b.textContent=deck[i];if(open.length===2){moves++;const [a,z]=open;if(deck[a]===deck[z]){matched.add(a);matched.add(z);setTimeout(()=>{open=[];draw()},300)}else setTimeout(()=>{open=[];draw()},650)}}};draw();}
  function colors(stage){let board=Array.from({length:64},()=>['red','blue','yellow','green','purple'][rand(5)]),score=0,seconds=45;const draw=()=>{stage.innerHTML='';toolbar(stage,`Score: ${score} · Time: ${seconds}s`,draw);const msg=document.createElement('div');msg.className='game-message';msg.textContent='Click two adjacent blocks of the same color.';stage.append(msg);const grid=document.createElement('div');grid.className='color-board';let first=-1;board.forEach((v,i)=>{const b=document.createElement('button');b.className='color-cell '+v;b.onclick=()=>{if(first<0){first=i;b.style.outline='4px solid #fff';return}const row=Math.floor(first/8),col=first%8,row2=Math.floor(i/8),col2=i%8;if(Math.abs(row-row2)+Math.abs(col-col2)!==1||board[i]!==board[first]){msg.textContent='Pick neighboring blocks with the same color.';first=-1;draw();return}board[first]='empty';board[i]='empty';score+=2;first=-1;for(let c=0;c<8;c++){let vals=[];for(let r=0;r<8;r++){const x=board[r*8+c];if(x!=='empty')vals.push(x)}for(let r=7;r>=0;r--)board[r*8+c]=vals.pop()||['red','blue','yellow','green','purple'][rand(5)]}draw()};grid.append(b)});stage.append(grid)};draw();}

  function fruit(stage){let score=0,time=30,active=true;const draw=()=>{stage.innerHTML='';toolbar(stage,`Score: ${score} · ${time}s`,draw);const msg=document.createElement('div');msg.className='game-message';msg.textContent='Slice the targets with clicks or taps.';stage.append(msg);const zone=document.createElement('div');zone.className='fruit-zone';stage.append(zone);function spawn(){if(!active)return;const f=document.createElement('button');f.className='fruit-target';f.textContent=['●','◆','●','✦'][rand(4)];f.style.left=(4+rand(88))+'%';f.style.bottom='-70px';zone.append(f);requestAnimationFrame(()=>{f.style.transition='bottom 1.7s linear,transform .3s';f.style.bottom=(18+rand(55))+'%';f.style.transform='rotate('+(rand(240)-120)+'deg)'});f.onclick=()=>{score++;f.remove()};setTimeout(()=>f.remove(),1800)}const spawnId=setInterval(spawn,520);const timer=setInterval(()=>{time--;if(time<=0){active=false;clearInterval(timer);clearInterval(spawnId);msg.textContent=`Time up! Final score: ${score}`}},1000);spawn();};draw();}

  function basket(stage){let score=0,streak=0,shooting=false;const draw=()=>{stage.innerHTML='';toolbar(stage,`Score: ${score} · Streak: ${streak}`,draw);const zone=document.createElement('div');zone.className='basket-zone';const board=document.createElement('div');board.className='basket-scoreboard';board.textContent='Tap the ball';const hoop=document.createElement('div');hoop.className='basket-hoop';hoop.style.left=(18+rand(58))+'%';const ball=document.createElement('button');ball.className='basket-ball';ball.onclick=()=>{if(shooting)return;shooting=true;const target=hoop.getBoundingClientRect(),b=ball.getBoundingClientRect();ball.style.left=(target.left-zone.getBoundingClientRect().left+target.width/2)+'px';ball.style.bottom='280px';setTimeout(()=>{const good=Math.random()<.72;if(good){score++;streak++;board.textContent='Swish!'}else{streak=0;board.textContent='Miss!'}shooting=false;draw()},500)};zone.append(board,hoop,ball);stage.append(zone)};draw();}

  function spin(stage){let spinning=false,rotation=0;stage.innerHTML='<div class="spin-stage"><div style="position:relative"><div class="wheel-pointer"></div><div class="wheel" id="wheel"></div></div><button class="mini-control" id="spinBtn">SPIN</button><div class="game-score" id="spinResult">Ready for a spin?</div></div>';const wheel=stage.querySelector('#wheel'),btn=stage.querySelector('#spinBtn'),res=stage.querySelector('#spinResult');btn.onclick=()=>{if(spinning)return;spinning=true;rotation+=1440+rand(720);wheel.style.transform=`rotate(${rotation}deg)`;setTimeout(()=>{const rewards=['+10 points','+25 points','Lucky round','Try again','Big smile','Bonus star','+50 points','Friend power'];res.textContent=rewards[rand(rewards.length)];spinning=false},2450)};}

  function slots(stage){let pos=0,bot=0,bot2=0,running=false;stage.innerHTML='<div class="game-toolbar"><span class="game-score" id="slotScore">Your car: 0%</span><button class="mini-control" id="boost">BOOST</button></div><div class="slots-track"><div class="slot-lane one"></div><div class="slot-lane two"></div><div class="slot-lane three"></div><div class="slot-car user" id="car"></div><div class="slot-car bot" id="botcar"></div><div class="slot-car bot2" id="botcar2"></div></div><div class="game-message" id="slotMsg">Press BOOST repeatedly to race. Bots drive automatically.</div>';const car=stage.querySelector('#car'),b=stage.querySelector('#botcar'),b2=stage.querySelector('#botcar2'),sc=stage.querySelector('#slotScore'),msg=stage.querySelector('#slotMsg');const timer=setInterval(()=>{if(pos>=100||bot>=100||bot2>=100){clearInterval(timer);return}bot+=1+rand(3);bot2+=1+rand(2);if(running)pos+=2;car.style.left=Math.min(pos,92)+'%';b.style.left=Math.min(bot,92)+'%';b2.style.left=Math.min(bot2,92)+'%';sc.textContent=`Your car: ${pos}%`;if(pos>=100){msg.textContent='You win the race!'}else if(bot>=100||bot2>=100){msg.textContent='A bot won. Hit BOOST faster next time.'}},220);stage.querySelector('#boost').onclick=()=>{running=true;pos+=4+rand(6);if(pos>=100)pos=100};}

  function snake(stage){let canvas,ctx,snake,food,dir,next,score,loop;function start(){stage.innerHTML='';const sc=toolbar(stage,'Score: 0',start);canvas=document.createElement('canvas');canvas.width=400;canvas.height=400;canvas.className='snake-canvas';stage.append(canvas);const pad=document.createElement('div');pad.className='mobile-pad';[['ArrowUp','↑'],['ArrowLeft','←'],['ArrowDown','↓'],['ArrowRight','→']].forEach(([k,t],i)=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>setDir(k);pad.append(b)});stage.append(pad);ctx=canvas.getContext('2d');snake=[{x:10,y:10},{x:9,y:10},{x:8,y:10}];food={x:16,y:14};dir={x:1,y:0};next={...dir};score=0;clearInterval(loop);loop=setInterval(tick,115);function setDir(k){const m={ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1},ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0}}[k];if(m&&!(m.x===-dir.x&&m.y===-dir.y))next=m}window.__snakeKey=e=>setDir(e.key)}document.removeEventListener('keydown',window.__snakeKey||(()=>{}));document.addEventListener('keydown',window.__snakeKey);function tick(){dir=next;const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(head.x<0||head.y<0||head.x>=20||head.y>=20||snake.some(s=>s.x===head.x&&s.y===head.y)){clearInterval(loop);alert(`Snake game over! Score: ${score}`);return}snake.unshift(head);if(head.x===food.x&&head.y===food.y){score++;food={x:rand(20),y:rand(20)};sc.textContent='Score: '+score}else snake.pop();ctx.clearRect(0,0,400,400);ctx.fillStyle='#b8e1b7';ctx.fillRect(0,0,400,400);ctx.fillStyle='#2c6b3c';snake.forEach((s,i)=>{ctx.fillStyle=i?'#4f9c5c':'#1f5e34';ctx.fillRect(s.x*20+1,s.y*20+1,18,18)});ctx.fillStyle='#df4d68';ctx.fillRect(food.x*20+3,food.y*20+3,14,14)}start();}

  function knife(stage){let count=0,angle=0,stuck=[];stage.innerHTML='<div class="knife-stage"><div class="knife-target" id="target"></div><button class="throw-knife" id="throw" aria-label="Throw knife"></button></div><div class="knife-count" id="knifeCount">Knives: 0 · Tap the handle to throw</div>';const target=stage.querySelector('#target'),btn=stage.querySelector('#throw'),label=stage.querySelector('#knifeCount');function throwKnife(){const danger=stuck.some(a=>Math.abs(((angle-a+540)%360)-180)<18);if(danger){label.textContent='Crash! Restart the game.';btn.disabled=true;return}stuck.push(angle);count++;label.textContent=`Knives: ${count}`;const k=document.createElement('span');k.className='knife-stuck';k.style.transform=`rotate(${angle}deg)`;target.append(k);angle=(angle+25+rand(35))%360;target.style.transform=`translateX(-50%) rotate(${angle}deg)`;if(count>=8){label.textContent='Target cleared! You win!';btn.disabled=true}}btn.onclick=throwKnife;}

  const games={ludo,carrom,snakes,tictactoe,chess,memory,colors,fruit,basket,spin,slots,snake,knife};
  function openGame(name){const fn=games[name];if(!fn)return;const card=document.querySelector(`[data-game="${name}"]`);setStage(card?.querySelector('h2')?.textContent||'Game','Offline mini-game · local only',fn)}
})();
